{
  "conferences" : [
    {
      "confTeams" : [
        {
          "abbreviation" : "UF",
          "state" : "Florida",
          "prestige" : "95",
          "name" : "Florida",
          "headCoach" : {
            "ratOff" : "82",
            "contractLength" : "6",
            "age" : "37",
            "startYear" : "2019",
            "cumulativePrestige" : "45",
            "ratDef" : "60",
            "homeState" : "Delaware",
            "ratPot" : "91",
            "ratTalent" : "84",
            "ratDiscipline" : "92",
            "baselinePrestige" : "95",
            "ratOvr" : "77",
            "name" : "James Gama",
            "contractYear" : "1"
          },
          "rival" : "UGA"
        },
        {
          "abbreviation" : "UGA",
          "state" : "Georgia",
          "prestige" : "95",
          "name" : "Georgia",
          "headCoach" : {
            "ratOff" : "76",
            "contractLength" : "6",
            "age" : "53",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "79",
            "homeState" : "California",
            "ratPot" : "87",
            "ratTalent" : "49",
            "ratDiscipline" : "93",
            "baselinePrestige" : "80",
            "ratOvr" : "74",
            "name" : "Lionel Saiki",
            "contractYear" : "1"
          },
          "rival" : "UF"
        },
        {
          "abbreviation" : "MIA",
          "state" : "Florida",
          "prestige" : "90",
          "name" : "Miami",
          "headCoach" : {
            "ratOff" : "74",
            "contractLength" : "6",
            "age" : "33",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "77",
            "homeState" : "Hawaii",
            "ratPot" : "56",
            "ratTalent" : "91",
            "ratDiscipline" : "61",
            "baselinePrestige" : "85",
            "ratOvr" : "75",
            "name" : "Dave Chicoine",
            "contractYear" : "1"
          },
          "rival" : "FSU"
        },
        {
          "abbreviation" : "FSU",
          "state" : "Florida",
          "prestige" : "85",
          "name" : "Florida State",
          "headCoach" : {
            "ratOff" : "63",
            "contractLength" : "6",
            "age" : "36",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "New Mexico",
            "ratPot" : "69",
            "ratTalent" : "70",
            "ratDiscipline" : "53",
            "baselinePrestige" : "90",
            "ratOvr" : "64",
            "name" : "Christian Koepke",
            "contractYear" : "1"
          },
          "rival" : "MIA"
        },
        {
          "abbreviation" : "UCF",
          "state" : "Florida",
          "prestige" : "78",
          "name" : "UCF",
          "headCoach" : {
            "ratOff" : "58",
            "contractLength" : "6",
            "age" : "47",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "79",
            "homeState" : "Michigan",
            "ratPot" : "81",
            "ratTalent" : "80",
            "ratDiscipline" : "70",
            "baselinePrestige" : "75",
            "ratOvr" : "71",
            "name" : "Andre Jablon",
            "contractYear" : "1"
          },
          "rival" : "USF"
        },
        {
          "abbreviation" : "USF",
          "state" : "Florida",
          "prestige" : "75",
          "name" : "USF",
          "headCoach" : {
            "ratOff" : "57",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "Texas",
            "ratPot" : "77",
            "ratTalent" : "77",
            "ratDiscipline" : "89",
            "baselinePrestige" : "75",
            "ratOvr" : "73",
            "name" : "Cedric Wdowiak",
            "contractYear" : "1"
          },
          "rival" : "UCF"
        },
        {
          "abbreviation" : "FAU",
          "state" : "Florida",
          "prestige" : "40",
          "name" : "FAU",
          "headCoach" : {
            "ratOff" : "58",
            "contractLength" : "6",
            "age" : "32",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "60",
            "homeState" : "Rhode Island",
            "ratPot" : "79",
            "ratTalent" : "55",
            "ratDiscipline" : "48",
            "baselinePrestige" : "70",
            "ratOvr" : "55",
            "name" : "Tom June",
            "contractYear" : "1"
          },
          "rival" : "FIU"
        },
        {
          "abbreviation" : "FIU",
          "state" : "Florida",
          "prestige" : "40",
          "name" : "FIU",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "42",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "67",
            "homeState" : "Tennessee",
            "ratPot" : "93",
            "ratTalent" : "74",
            "ratDiscipline" : "70",
            "baselinePrestige" : "65",
            "ratOvr" : "68",
            "name" : "Gerard Rodeigues",
            "contractYear" : "1"
          },
          "rival" : "FAU"
        },
        {
          "abbreviation" : "GTECH",
          "state" : "Georgia",
          "prestige" : "75",
          "name" : "Georgia Tech",
          "headCoach" : {
            "ratOff" : "55",
            "contractLength" : "6",
            "age" : "51",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "53",
            "homeState" : "Utah",
            "ratPot" : "61",
            "ratTalent" : "49",
            "ratDiscipline" : "47",
            "baselinePrestige" : "65",
            "ratOvr" : "51",
            "name" : "Bill Clites",
            "contractYear" : "1"
          },
          "rival" : "GSU"
        },
        {
          "abbreviation" : "GSU",
          "state" : "Georgia State",
          "prestige" : "40",
          "name" : "Georgia State",
          "headCoach" : {
            "ratOff" : "65",
            "contractLength" : "6",
            "age" : "37",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "Indiana",
            "ratPot" : "70",
            "ratTalent" : "69",
            "ratDiscipline" : "69",
            "baselinePrestige" : "50",
            "ratOvr" : "68",
            "name" : "Alejandro Navarro",
            "contractYear" : "1"
          },
          "rival" : "GTECH"
        }
      ],
      "confFullName" : "Gulf South",
      "confPrestige" : "85",
      "confName" : "GULF"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "OSU",
          "state" : "Ohio",
          "prestige" : "95",
          "name" : "Ohio State",
          "headCoach" : {
            "ratOff" : "73",
            "contractLength" : "6",
            "age" : "45",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "Ohio",
            "ratPot" : "80",
            "ratTalent" : "54",
            "ratDiscipline" : "86",
            "baselinePrestige" : "90",
            "ratOvr" : "69",
            "name" : "Dakota Pockrus",
            "contractYear" : "1"
          },
          "rival" : "CINCY"
        },
        {
          "abbreviation" : "CINCY",
          "state" : "Ohio",
          "prestige" : "70",
          "name" : "Cincinatti",
          "headCoach" : {
            "ratOff" : "63",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "64",
            "homeState" : "North Dakota",
            "ratPot" : "57",
            "ratTalent" : "78",
            "ratDiscipline" : "81",
            "baselinePrestige" : "90",
            "ratOvr" : "71",
            "name" : "Dylan Leiper",
            "contractYear" : "1"
          },
          "rival" : "OSU"
        },
        {
          "abbreviation" : "MICH",
          "state" : "Michigan",
          "prestige" : "90",
          "name" : "Michigan",
          "headCoach" : {
            "ratOff" : "71",
            "contractLength" : "6",
            "age" : "39",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "64",
            "homeState" : "New York",
            "ratPot" : "64",
            "ratTalent" : "45",
            "ratDiscipline" : "65",
            "baselinePrestige" : "80",
            "ratOvr" : "61",
            "name" : "Jamal Yueh",
            "contractYear" : "1"
          },
          "rival" : "MSU"
        },
        {
          "abbreviation" : "MSU",
          "state" : "Michigan",
          "prestige" : "80",
          "name" : "Michigan State",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "56",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "71",
            "homeState" : "Oregon",
            "ratPot" : "90",
            "ratTalent" : "64",
            "ratDiscipline" : "64",
            "baselinePrestige" : "70",
            "ratOvr" : "65",
            "name" : "Ellis Straiton",
            "contractYear" : "1"
          },
          "rival" : "MICH"
        },
        {
          "abbreviation" : "INDY",
          "state" : "Indiana",
          "prestige" : "70",
          "name" : "Indiana",
          "headCoach" : {
            "ratOff" : "55",
            "contractLength" : "6",
            "age" : "34",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Minnesota",
            "ratPot" : "77",
            "ratTalent" : "68",
            "ratDiscipline" : "93",
            "baselinePrestige" : "55",
            "ratOvr" : "68",
            "name" : "Austin Hoepfner",
            "contractYear" : "1"
          },
          "rival" : "PUR"
        },
        {
          "abbreviation" : "PUR",
          "state" : "Indiana",
          "prestige" : "70",
          "name" : "Purdue",
          "headCoach" : {
            "ratOff" : "76",
            "contractLength" : "6",
            "age" : "41",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "Rhode Island",
            "ratPot" : "85",
            "ratTalent" : "59",
            "ratDiscipline" : "85",
            "baselinePrestige" : "70",
            "ratOvr" : "73",
            "name" : "Troy Arteaga",
            "contractYear" : "1"
          },
          "rival" : "INDY"
        },
        {
          "abbreviation" : "BALL",
          "state" : "Indiana",
          "prestige" : "45",
          "name" : "Ball State",
          "headCoach" : {
            "ratOff" : "50",
            "contractLength" : "6",
            "age" : "49",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "54",
            "homeState" : "Alaska",
            "ratPot" : "92",
            "ratTalent" : "73",
            "ratDiscipline" : "75",
            "baselinePrestige" : "45",
            "ratOvr" : "63",
            "name" : "Tupac Isa",
            "contractYear" : "1"
          },
          "rival" : "KENT"
        },
        {
          "abbreviation" : "KENT",
          "state" : "OHIO",
          "prestige" : "45",
          "name" : "Kent State",
          "headCoach" : {
            "ratOff" : "66",
            "contractLength" : "6",
            "age" : "38",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "54",
            "homeState" : "Idaho",
            "ratPot" : "75",
            "ratTalent" : "84",
            "ratDiscipline" : "50",
            "baselinePrestige" : "65",
            "ratOvr" : "63",
            "name" : "Lonnie Mutschelknaus",
            "contractYear" : "1"
          },
          "rival" : "BALL"
        },
        {
          "abbreviation" : "OHIO",
          "state" : "Ohio",
          "prestige" : "50",
          "name" : "Ohio",
          "headCoach" : {
            "ratOff" : "68",
            "contractLength" : "6",
            "age" : "44",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "62",
            "homeState" : "Delaware",
            "ratPot" : "61",
            "ratTalent" : "63",
            "ratDiscipline" : "47",
            "baselinePrestige" : "70",
            "ratOvr" : "60",
            "name" : "Dominic Schikora",
            "contractYear" : "1"
          },
          "rival" : "TOL"
        },
        {
          "abbreviation" : "TOL",
          "state" : "Ohio",
          "prestige" : "45",
          "name" : "Toledo",
          "headCoach" : {
            "ratOff" : "79",
            "contractLength" : "6",
            "age" : "50",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Nevada",
            "ratPot" : "66",
            "ratTalent" : "91",
            "ratDiscipline" : "69",
            "baselinePrestige" : "65",
            "ratOvr" : "77",
            "name" : "Jermaine Thiry",
            "contractYear" : "1"
          },
          "rival" : "OHIO"
        }
      ],
      "confFullName" : "Great Lakes",
      "confPrestige" : "85",
      "confName" : "LAKES"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "WIS",
          "state" : "Wisconsin",
          "prestige" : "80",
          "name" : "Wisconsin",
          "headCoach" : {
            "ratOff" : "81",
            "contractLength" : "6",
            "age" : "37",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "64",
            "homeState" : "Ohio",
            "ratPot" : "66",
            "ratTalent" : "86",
            "ratDiscipline" : "85",
            "baselinePrestige" : "75",
            "ratOvr" : "79",
            "name" : "Martin Malacara",
            "contractYear" : "1"
          },
          "rival" : "IOWA"
        },
        {
          "abbreviation" : "NEB",
          "state" : "Nebraska",
          "prestige" : "68",
          "name" : "Nebraska",
          "headCoach" : {
            "ratOff" : "67",
            "contractLength" : "6",
            "age" : "55",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "81",
            "homeState" : "Alaska",
            "ratPot" : "88",
            "ratTalent" : "56",
            "ratDiscipline" : "85",
            "baselinePrestige" : "90",
            "ratOvr" : "72",
            "name" : "Jermaine Johnsey",
            "contractYear" : "1"
          },
          "rival" : "MIZZ"
        },
        {
          "abbreviation" : "IOWA",
          "state" : "Iowa",
          "prestige" : "80",
          "name" : "Iowa",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "48",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "65",
            "homeState" : "Washington",
            "ratPot" : "75",
            "ratTalent" : "76",
            "ratDiscipline" : "65",
            "baselinePrestige" : "65",
            "ratOvr" : "66",
            "name" : "Kasim Tailor",
            "contractYear" : "1"
          },
          "rival" : "WIS"
        },
        {
          "abbreviation" : "ISU",
          "state" : "Iowa",
          "prestige" : "74",
          "name" : "Iowa State",
          "headCoach" : {
            "ratOff" : "57",
            "contractLength" : "6",
            "age" : "35",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "65",
            "homeState" : "Kansas",
            "ratPot" : "84",
            "ratTalent" : "65",
            "ratDiscipline" : "74",
            "baselinePrestige" : "45",
            "ratOvr" : "65",
            "name" : "Weldon Faircloth",
            "contractYear" : "1"
          },
          "rival" : "KSU"
        },
        {
          "abbreviation" : "MIZZ",
          "state" : "Missouri",
          "prestige" : "72",
          "name" : "Missouri",
          "headCoach" : {
            "ratOff" : "76",
            "contractLength" : "6",
            "age" : "47",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "60",
            "homeState" : "Virginia",
            "ratPot" : "84",
            "ratTalent" : "62",
            "ratDiscipline" : "71",
            "baselinePrestige" : "75",
            "ratOvr" : "67",
            "name" : "Terrence Holla",
            "contractYear" : "1"
          },
          "rival" : "NEB"
        },
        {
          "abbreviation" : "KSU",
          "state" : "Kansas",
          "prestige" : "70",
          "name" : "Kansas State",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "43",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "89",
            "homeState" : "Colorado",
            "ratPot" : "87",
            "ratTalent" : "92",
            "ratDiscipline" : "68",
            "baselinePrestige" : "85",
            "ratOvr" : "93",
            "name" : "C Fransua",
            "contractYear" : "1"
          },
          "rival" : "ISU"
        },
        {
          "abbreviation" : "MINN",
          "state" : "Minnesota",
          "prestige" : "72",
          "name" : "Minnesota",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "48",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "62",
            "homeState" : "Montana",
            "ratPot" : "95",
            "ratTalent" : "79",
            "ratDiscipline" : "76",
            "baselinePrestige" : "50",
            "ratOvr" : "70",
            "name" : "Joseph Hagopian",
            "contractYear" : "1"
          },
          "rival" : "NDSU"
        },
        {
          "abbreviation" : "NDSU",
          "state" : "North Dakota",
          "prestige" : "72",
          "name" : "North Dakota State",
          "headCoach" : {
            "ratOff" : "75",
            "contractLength" : "6",
            "age" : "56",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "Rhode Island",
            "ratPot" : "95",
            "ratTalent" : "88",
            "ratDiscipline" : "77",
            "baselinePrestige" : "85",
            "ratOvr" : "78",
            "name" : "Cody Stouffer",
            "contractYear" : "1"
          },
          "rival" : "MINN"
        },
        {
          "abbreviation" : "CMU",
          "state" : "Michigan",
          "prestige" : "55",
          "name" : "Central Michigan",
          "headCoach" : {
            "ratOff" : "75",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "68",
            "homeState" : "Missouri",
            "ratPot" : "92",
            "ratTalent" : "90",
            "ratDiscipline" : "45",
            "baselinePrestige" : "70",
            "ratOvr" : "69",
            "name" : "Jarvis Arsham",
            "contractYear" : "1"
          },
          "rival" : "KU"
        },
        {
          "abbreviation" : "KU",
          "state" : "Kansas",
          "prestige" : "40",
          "name" : "Kansas",
          "headCoach" : {
            "ratOff" : "67",
            "contractLength" : "6",
            "age" : "44",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "71",
            "homeState" : "Tennessee",
            "ratPot" : "61",
            "ratTalent" : "70",
            "ratDiscipline" : "81",
            "baselinePrestige" : "70",
            "ratOvr" : "72",
            "name" : "Joey Unrein",
            "contractYear" : "1"
          },
          "rival" : "CMU"
        }
      ],
      "confFullName" : "Valley",
      "confPrestige" : "83",
      "confName" : "VALLEY"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "USC",
          "state" : "California",
          "prestige" : "89",
          "name" : "USC",
          "headCoach" : {
            "ratOff" : "68",
            "contractLength" : "6",
            "age" : "56",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Rhode Island",
            "ratPot" : "86",
            "ratTalent" : "90",
            "ratDiscipline" : "58",
            "baselinePrestige" : "70",
            "ratOvr" : "71",
            "name" : "Alvin Canseco",
            "contractYear" : "1"
          },
          "rival" : "UCLA"
        },
        {
          "abbreviation" : "ORE",
          "state" : "Oregon",
          "prestige" : "84",
          "name" : "Oregon",
          "headCoach" : {
            "ratOff" : "75",
            "contractLength" : "6",
            "age" : "31",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "74",
            "homeState" : "Hawaii",
            "ratPot" : "55",
            "ratTalent" : "64",
            "ratDiscipline" : "50",
            "baselinePrestige" : "90",
            "ratOvr" : "65",
            "name" : "Malik Tofte",
            "contractYear" : "1"
          },
          "rival" : "ORST"
        },
        {
          "abbreviation" : "UCLA",
          "state" : "California",
          "prestige" : "88",
          "name" : "UCLA",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "64",
            "homeState" : "Connecticut",
            "ratPot" : "74",
            "ratTalent" : "78",
            "ratDiscipline" : "54",
            "baselinePrestige" : "70",
            "ratOvr" : "64",
            "name" : "Xavier Predovich",
            "contractYear" : "1"
          },
          "rival" : "USC"
        },
        {
          "abbreviation" : "STAN",
          "state" : "California",
          "prestige" : "78",
          "name" : "Stanford",
          "headCoach" : {
            "ratOff" : "55",
            "contractLength" : "6",
            "age" : "56",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "Michigan",
            "ratPot" : "83",
            "ratTalent" : "72",
            "ratDiscipline" : "93",
            "baselinePrestige" : "60",
            "ratOvr" : "71",
            "name" : "Marc Monarca",
            "contractYear" : "1"
          },
          "rival" : "CAL"
        },
        {
          "abbreviation" : "UW",
          "state" : "Washington",
          "prestige" : "84",
          "name" : "Washington",
          "headCoach" : {
            "ratOff" : "73",
            "contractLength" : "6",
            "age" : "57",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Kentucky",
            "ratPot" : "94",
            "ratTalent" : "78",
            "ratDiscipline" : "93",
            "baselinePrestige" : "80",
            "ratOvr" : "78",
            "name" : "Jackie Westbrook",
            "contractYear" : "1"
          },
          "rival" : "WSU"
        },
        {
          "abbreviation" : "SDSU",
          "state" : "California",
          "prestige" : "53",
          "name" : "San Diego State",
          "headCoach" : {
            "ratOff" : "57",
            "contractLength" : "6",
            "age" : "32",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "56",
            "homeState" : "Maryland",
            "ratPot" : "83",
            "ratTalent" : "90",
            "ratDiscipline" : "62",
            "baselinePrestige" : "55",
            "ratOvr" : "66",
            "name" : "Clifton Hauschildt",
            "contractYear" : "1"
          },
          "rival" : "HAW"
        },
        {
          "abbreviation" : "CAL",
          "state" : "California",
          "prestige" : "78",
          "name" : "California",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "50",
            "homeState" : "New Jersey",
            "ratPot" : "52",
            "ratTalent" : "68",
            "ratDiscipline" : "84",
            "baselinePrestige" : "60",
            "ratOvr" : "65",
            "name" : "Brian Moehrle",
            "contractYear" : "1"
          },
          "rival" : "STAN"
        },
        {
          "abbreviation" : "ORST",
          "state" : "Oregon",
          "prestige" : "60",
          "name" : "Oregon State",
          "headCoach" : {
            "ratOff" : "56",
            "contractLength" : "6",
            "age" : "53",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "67",
            "homeState" : "Wyoming",
            "ratPot" : "69",
            "ratTalent" : "81",
            "ratDiscipline" : "63",
            "baselinePrestige" : "90",
            "ratOvr" : "66",
            "name" : "Donnell Tiboni",
            "contractYear" : "1"
          },
          "rival" : "ORE"
        },
        {
          "abbreviation" : "WSU",
          "state" : "Washington",
          "prestige" : "61",
          "name" : "Washington State",
          "headCoach" : {
            "ratOff" : "72",
            "contractLength" : "6",
            "age" : "47",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "Ohio",
            "ratPot" : "94",
            "ratTalent" : "87",
            "ratDiscipline" : "94",
            "baselinePrestige" : "80",
            "ratOvr" : "79",
            "name" : "Kenny Humetewa",
            "contractYear" : "1"
          },
          "rival" : "UW"
        },
        {
          "abbreviation" : "HAW",
          "state" : "Hawaii",
          "prestige" : "59",
          "name" : "Hawaii",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "34",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "South Dakota",
            "ratPot" : "86",
            "ratTalent" : "52",
            "ratDiscipline" : "72",
            "baselinePrestige" : "50",
            "ratOvr" : "62",
            "name" : "Ashton Flanagin",
            "contractYear" : "1"
          },
          "rival" : "ASU"
        }
      ],
      "confFullName" : "Pacific",
      "confPrestige" : "85",
      "confName" : "PAC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "TENN",
          "state" : "Tennessee",
          "prestige" : "85",
          "name" : "Tennessee",
          "headCoach" : {
            "ratOff" : "79",
            "contractLength" : "6",
            "age" : "40",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "65",
            "homeState" : "Tennessee",
            "ratPot" : "61",
            "ratTalent" : "67",
            "ratDiscipline" : "66",
            "baselinePrestige" : "70",
            "ratOvr" : "67",
            "name" : "Kendric Barbo",
            "contractYear" : "1"
          },
          "rival" : "VANDY"
        },
        {
          "abbreviation" : "WVU",
          "state" : "West Virginia",
          "prestige" : "72",
          "name" : "West Virginia",
          "headCoach" : {
            "ratOff" : "95",
            "contractLength" : "6",
            "age" : "32",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "93",
            "homeState" : "South Carolina",
            "ratPot" : "95",
            "ratTalent" : "95",
            "ratDiscipline" : "89",
            "baselinePrestige" : "89",
            "ratOvr" : "95",
            "name" : "R Nunez",
            "contractYear" : "1"
          },
          "rival" : "MAR"
        },
        {
          "abbreviation" : "NW",
          "state" : "Illinois",
          "prestige" : "80",
          "name" : "Northwestern",
          "headCoach" : {
            "ratOff" : "76",
            "contractLength" : "6",
            "age" : "55",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "55",
            "homeState" : "Texas",
            "ratPot" : "91",
            "ratTalent" : "45",
            "ratDiscipline" : "69",
            "baselinePrestige" : "75",
            "ratOvr" : "61",
            "name" : "Hunter Tranum",
            "contractYear" : "1"
          },
          "rival" : "ILLI"
        },
        {
          "abbreviation" : "ILLI",
          "state" : "Illinois",
          "prestige" : "70",
          "name" : "Illinois",
          "headCoach" : {
            "ratOff" : "68",
            "contractLength" : "6",
            "age" : "45",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "76",
            "homeState" : "South Dakota",
            "ratPot" : "72",
            "ratTalent" : "51",
            "ratDiscipline" : "50",
            "baselinePrestige" : "80",
            "ratOvr" : "61",
            "name" : "DJ Paparelli",
            "contractYear" : "1"
          },
          "rival" : "NW"
        },
        {
          "abbreviation" : "VANDY",
          "state" : "Tennessee",
          "prestige" : "67",
          "name" : "Vanderbilt",
          "headCoach" : {
            "ratOff" : "78",
            "contractLength" : "6",
            "age" : "44",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "68",
            "homeState" : "New York",
            "ratPot" : "67",
            "ratTalent" : "89",
            "ratDiscipline" : "88",
            "baselinePrestige" : "70",
            "ratOvr" : "80",
            "name" : "Kevin Schuchat",
            "contractYear" : "1"
          },
          "rival" : "TENN"
        },
        {
          "abbreviation" : "UK",
          "state" : "Kentucky",
          "prestige" : "69",
          "name" : "Kentucky",
          "headCoach" : {
            "ratOff" : "71",
            "contractLength" : "6",
            "age" : "51",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "64",
            "homeState" : "Wyoming",
            "ratPot" : "81",
            "ratTalent" : "87",
            "ratDiscipline" : "50",
            "baselinePrestige" : "70",
            "ratOvr" : "68",
            "name" : "Neil Carullo",
            "contractYear" : "1"
          },
          "rival" : "LOU"
        },
        {
          "abbreviation" : "LOU",
          "state" : "Kentucky",
          "prestige" : "75",
          "name" : "Louisville",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "75",
            "homeState" : "Hawaii",
            "ratPot" : "89",
            "ratTalent" : "67",
            "ratDiscipline" : "87",
            "baselinePrestige" : "90",
            "ratOvr" : "73",
            "name" : "Charles Fatzinger",
            "contractYear" : "1"
          },
          "rival" : "UK"
        },
        {
          "abbreviation" : "MAR",
          "state" : "West Virginia",
          "prestige" : "55",
          "name" : "Marshall",
          "headCoach" : {
            "ratOff" : "81",
            "contractLength" : "6",
            "age" : "32",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "64",
            "homeState" : "Mississippi",
            "ratPot" : "65",
            "ratTalent" : "52",
            "ratDiscipline" : "45",
            "baselinePrestige" : "85",
            "ratOvr" : "60",
            "name" : "Walter Nowland",
            "contractYear" : "1"
          },
          "rival" : "WVU"
        },
        {
          "abbreviation" : "WKU",
          "state" : "Kentucky",
          "prestige" : "52",
          "name" : "Western Kentucky",
          "headCoach" : {
            "ratOff" : "62",
            "contractLength" : "6",
            "age" : "49",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "69",
            "homeState" : "Indiana",
            "ratPot" : "68",
            "ratTalent" : "86",
            "ratDiscipline" : "74",
            "baselinePrestige" : "60",
            "ratOvr" : "72",
            "name" : "Hudson Nuzzi",
            "contractYear" : "1"
          },
          "rival" : "MT"
        },
        {
          "abbreviation" : "MT",
          "state" : "Tennessee",
          "prestige" : "52",
          "name" : "Middle Tennessee",
          "headCoach" : {
            "ratOff" : "48",
            "contractLength" : "6",
            "age" : "44",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "61",
            "homeState" : "Arizona",
            "ratPot" : "95",
            "ratTalent" : "60",
            "ratDiscipline" : "74",
            "baselinePrestige" : "25",
            "ratOvr" : "60",
            "name" : "Duke Obas",
            "contractYear" : "1"
          },
          "rival" : "WKU"
        }
      ],
      "confFullName" : "Mid-American",
      "confPrestige" : "83",
      "confName" : "Mid-Am"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "APP",
          "state" : "North Carolina",
          "prestige" : "55",
          "name" : "Appalachian State",
          "headCoach" : {
            "ratOff" : "68",
            "contractLength" : "6",
            "age" : "39",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "75",
            "homeState" : "Wyoming",
            "ratPot" : "65",
            "ratTalent" : "58",
            "ratDiscipline" : "80",
            "baselinePrestige" : "80",
            "ratOvr" : "70",
            "name" : "Hans Rackett",
            "contractYear" : "1"
          },
          "rival" : "ECU"
        },
        {
          "abbreviation" : "CLEM",
          "state" : "South Carolina",
          "prestige" : "95",
          "name" : "Clemson",
          "headCoach" : {
            "ratOff" : "61",
            "contractLength" : "6",
            "age" : "39",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "Rhode Island",
            "ratPot" : "79",
            "ratTalent" : "53",
            "ratDiscipline" : "86",
            "baselinePrestige" : "75",
            "ratOvr" : "68",
            "name" : "JR Perriello",
            "contractYear" : "1"
          },
          "rival" : "SC"
        },
        {
          "abbreviation" : "ECU",
          "state" : "North Carolina",
          "prestige" : "55",
          "name" : "East Carolina",
          "headCoach" : {
            "ratOff" : "68",
            "contractLength" : "6",
            "age" : "40",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "65",
            "homeState" : "Alabama",
            "ratPot" : "77",
            "ratTalent" : "91",
            "ratDiscipline" : "83",
            "baselinePrestige" : "75",
            "ratOvr" : "76",
            "name" : "Jason Gura",
            "contractYear" : "1"
          },
          "rival" : "APP"
        },
        {
          "abbreviation" : "VT",
          "state" : "Virginia",
          "prestige" : "70",
          "name" : "Virgina Tech",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "57",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "76",
            "homeState" : "North Carolina",
            "ratPot" : "80",
            "ratTalent" : "47",
            "ratDiscipline" : "67",
            "baselinePrestige" : "55",
            "ratOvr" : "62",
            "name" : "Devante Gjerde",
            "contractYear" : "1"
          },
          "rival" : "UVA"
        },
        {
          "abbreviation" : "UNC",
          "state" : "North Carolina",
          "prestige" : "80",
          "name" : "North Carolina",
          "headCoach" : {
            "ratOff" : "55",
            "contractLength" : "6",
            "age" : "55",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Minnesota",
            "ratPot" : "74",
            "ratTalent" : "63",
            "ratDiscipline" : "93",
            "baselinePrestige" : "45",
            "ratOvr" : "67",
            "name" : "Derrick Pyron",
            "contractYear" : "1"
          },
          "rival" : "DUKE"
        },
        {
          "abbreviation" : "DUKE",
          "state" : "North Carolina",
          "prestige" : "65",
          "name" : "Duke",
          "headCoach" : {
            "ratOff" : "65",
            "contractLength" : "6",
            "age" : "51",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "56",
            "homeState" : "New York",
            "ratPot" : "55",
            "ratTalent" : "85",
            "ratDiscipline" : "53",
            "baselinePrestige" : "50",
            "ratOvr" : "64",
            "name" : "Jimmie Sterry",
            "contractYear" : "1"
          },
          "rival" : "UNC"
        },
        {
          "abbreviation" : "SC",
          "state" : "South Carolina",
          "prestige" : "70",
          "name" : "South Carolina",
          "headCoach" : {
            "ratOff" : "67",
            "contractLength" : "6",
            "age" : "42",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "63",
            "homeState" : "Massachusetts",
            "ratPot" : "63",
            "ratTalent" : "60",
            "ratDiscipline" : "74",
            "baselinePrestige" : "65",
            "ratOvr" : "66",
            "name" : "Derrick Carston",
            "contractYear" : "1"
          },
          "rival" : "CLEM"
        },
        {
          "abbreviation" : "NCST",
          "state" : "North Carolina",
          "prestige" : "65",
          "name" : "NC State",
          "headCoach" : {
            "ratOff" : "74",
            "contractLength" : "6",
            "age" : "40",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "68",
            "homeState" : "Florida",
            "ratPot" : "57",
            "ratTalent" : "55",
            "ratDiscipline" : "58",
            "baselinePrestige" : "70",
            "ratOvr" : "62",
            "name" : "Kene Aluise",
            "contractYear" : "1"
          },
          "rival" : "WF"
        },
        {
          "abbreviation" : "UVA",
          "state" : "Virginia",
          "prestige" : "65",
          "name" : "Virginia",
          "headCoach" : {
            "ratOff" : "56",
            "contractLength" : "6",
            "age" : "43",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "73",
            "homeState" : "Wyoming",
            "ratPot" : "91",
            "ratTalent" : "79",
            "ratDiscipline" : "83",
            "baselinePrestige" : "60",
            "ratOvr" : "72",
            "name" : "Antwan Ngueyn",
            "contractYear" : "1"
          },
          "rival" : "VT"
        },
        {
          "abbreviation" : "WAKE",
          "state" : "North Carolina",
          "prestige" : "55",
          "name" : "Wake Forest",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "47",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Vermont",
            "ratPot" : "95",
            "ratTalent" : "72",
            "ratDiscipline" : "53",
            "baselinePrestige" : "75",
            "ratOvr" : "61",
            "name" : "Jerry Horn",
            "contractYear" : "1"
          },
          "rival" : "NCST"
        }
      ],
      "confFullName" : "Atlantic Coast",
      "confPrestige" : "85",
      "confName" : "ACC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "OU",
          "state" : "Oklahoma",
          "prestige" : "95",
          "name" : "Oklahoma",
          "headCoach" : {
            "ratOff" : "57",
            "contractLength" : "6",
            "age" : "40",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "62",
            "homeState" : "Louisiana",
            "ratPot" : "90",
            "ratTalent" : "87",
            "ratDiscipline" : "73",
            "baselinePrestige" : "65",
            "ratOvr" : "69",
            "name" : "Ronald Windrow",
            "contractYear" : "1"
          },
          "rival" : "TEX"
        },
        {
          "abbreviation" : "TCU",
          "state" : "Texas",
          "prestige" : "65",
          "name" : "Texas Christian",
          "headCoach" : {
            "ratOff" : "51",
            "contractLength" : "6",
            "age" : "50",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "56",
            "homeState" : "Tennessee",
            "ratPot" : "60",
            "ratTalent" : "47",
            "ratDiscipline" : "51",
            "baselinePrestige" : "45",
            "ratOvr" : "51",
            "name" : "Brogan Garcelon",
            "contractYear" : "1"
          },
          "rival" : "SMU"
        },
        {
          "abbreviation" : "HOU",
          "state" : "Texas",
          "prestige" : "72",
          "name" : "Houston",
          "headCoach" : {
            "ratOff" : "59",
            "contractLength" : "6",
            "age" : "31",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "61",
            "homeState" : "Minnesota",
            "ratPot" : "93",
            "ratTalent" : "94",
            "ratDiscipline" : "45",
            "baselinePrestige" : "55",
            "ratOvr" : "64",
            "name" : "Wallace Luvene",
            "contractYear" : "1"
          },
          "rival" : "BAY"
        },
        {
          "abbreviation" : "SMU",
          "state" : "Texas",
          "prestige" : "64",
          "name" : "SMU",
          "headCoach" : {
            "ratOff" : "70",
            "contractLength" : "6",
            "age" : "45",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Arizona",
            "ratPot" : "82",
            "ratTalent" : "61",
            "ratDiscipline" : "81",
            "baselinePrestige" : "50",
            "ratOvr" : "67",
            "name" : "Melvin Stroffolino",
            "contractYear" : "1"
          },
          "rival" : "TCU"
        },
        {
          "abbreviation" : "TEX",
          "state" : "Texas",
          "prestige" : "90",
          "name" : "Texas",
          "headCoach" : {
            "ratOff" : "67",
            "contractLength" : "6",
            "age" : "51",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "60",
            "homeState" : "Pennsylvania",
            "ratPot" : "50",
            "ratTalent" : "70",
            "ratDiscipline" : "54",
            "baselinePrestige" : "75",
            "ratOvr" : "62",
            "name" : "Derrick Bawek",
            "contractYear" : "1"
          },
          "rival" : "OU"
        },
        {
          "abbreviation" : "BAY",
          "state" : "Texas",
          "prestige" : "75",
          "name" : "Baylor",
          "headCoach" : {
            "ratOff" : "53",
            "contractLength" : "6",
            "age" : "38",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "68",
            "homeState" : "Alaska",
            "ratPot" : "64",
            "ratTalent" : "46",
            "ratDiscipline" : "45",
            "baselinePrestige" : "60",
            "ratOvr" : "53",
            "name" : "Seth Maceyak",
            "contractYear" : "1"
          },
          "rival" : "HOU"
        },
        {
          "abbreviation" : "TTU",
          "state" : "Texas",
          "prestige" : "70",
          "name" : "Texas Tech",
          "headCoach" : {
            "ratOff" : "67",
            "contractLength" : "6",
            "age" : "51",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "65",
            "homeState" : "North Dakota",
            "ratPot" : "51",
            "ratTalent" : "79",
            "ratDiscipline" : "81",
            "baselinePrestige" : "75",
            "ratOvr" : "73",
            "name" : "Emmanuel Kerbo",
            "contractYear" : "1"
          },
          "rival" : "TAMU"
        },
        {
          "abbreviation" : "TAMU",
          "state" : "Texas",
          "prestige" : "85",
          "name" : "Texas A&M",
          "headCoach" : {
            "ratOff" : "69",
            "contractLength" : "6",
            "age" : "43",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "Ohio",
            "ratPot" : "55",
            "ratTalent" : "75",
            "ratDiscipline" : "83",
            "baselinePrestige" : "70",
            "ratOvr" : "73",
            "name" : "Andy Anspach",
            "contractYear" : "1"
          },
          "rival" : "TTU"
        },
        {
          "abbreviation" : "OKST",
          "state" : "Oklahoma",
          "prestige" : "70",
          "name" : "Oklahoma State",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "49",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "Indiana",
            "ratPot" : "62",
            "ratTalent" : "74",
            "ratDiscipline" : "66",
            "baselinePrestige" : "70",
            "ratOvr" : "66",
            "name" : "Bill Harrell",
            "contractYear" : "1"
          },
          "rival" : "UNT"
        },
        {
          "abbreviation" : "UNT",
          "state" : "Texas",
          "prestige" : "40",
          "name" : "North Texas",
          "headCoach" : {
            "ratOff" : "71",
            "contractLength" : "6",
            "age" : "43",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "65",
            "homeState" : "Mississippi",
            "ratPot" : "52",
            "ratTalent" : "82",
            "ratDiscipline" : "66",
            "baselinePrestige" : "70",
            "ratOvr" : "71",
            "name" : "Darryl Calvaruso",
            "contractYear" : "1"
          },
          "rival" : "OKST"
        }
      ],
      "confFullName" : "Western Athletic",
      "confPrestige" : "86",
      "confName" : "WAC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "BYU",
          "state" : "Utah",
          "prestige" : "65",
          "name" : "Brigham Young",
          "headCoach" : {
            "ratOff" : "68",
            "contractLength" : "6",
            "age" : "36",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "68",
            "homeState" : "Wisconsin",
            "ratPot" : "66",
            "ratTalent" : "57",
            "ratDiscipline" : "78",
            "baselinePrestige" : "75",
            "ratOvr" : "67",
            "name" : "Zack Guzzi",
            "contractYear" : "1"
          },
          "rival" : "UTAH"
        },
        {
          "abbreviation" : "UTAH",
          "state" : "Utah",
          "prestige" : "60",
          "name" : "Utah",
          "headCoach" : {
            "ratOff" : "71",
            "contractLength" : "6",
            "age" : "49",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Idaho",
            "ratPot" : "63",
            "ratTalent" : "74",
            "ratDiscipline" : "63",
            "baselinePrestige" : "80",
            "ratOvr" : "69",
            "name" : "Fred Tone",
            "contractYear" : "1"
          },
          "rival" : "BYU"
        },
        {
          "abbreviation" : "AF",
          "state" : "Colorado",
          "prestige" : "50",
          "name" : "Air Force",
          "headCoach" : {
            "ratOff" : "73",
            "contractLength" : "6",
            "age" : "35",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "69",
            "homeState" : "Hawaii",
            "ratPot" : "72",
            "ratTalent" : "61",
            "ratDiscipline" : "59",
            "baselinePrestige" : "70",
            "ratOvr" : "65",
            "name" : "AJ Dorlando",
            "contractYear" : "1"
          },
          "rival" : "COL"
        },
        {
          "abbreviation" : "WYO",
          "state" : "Wyoming",
          "prestige" : "40",
          "name" : "Wyoming",
          "headCoach" : {
            "ratOff" : "72",
            "contractLength" : "6",
            "age" : "42",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "South Dakota",
            "ratPot" : "62",
            "ratTalent" : "61",
            "ratDiscipline" : "77",
            "baselinePrestige" : "50",
            "ratOvr" : "70",
            "name" : "Max Belli",
            "contractYear" : "1"
          },
          "rival" : "CSU"
        },
        {
          "abbreviation" : "CSU",
          "state" : "Colorado",
          "prestige" : "50",
          "name" : "Colorado St",
          "headCoach" : {
            "ratOff" : "61",
            "contractLength" : "6",
            "age" : "37",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "63",
            "homeState" : "Wisconsin",
            "ratPot" : "55",
            "ratTalent" : "70",
            "ratDiscipline" : "82",
            "baselinePrestige" : "70",
            "ratOvr" : "69",
            "name" : "Trumaine Sau",
            "contractYear" : "1"
          },
          "rival" : "WYO"
        },
        {
          "abbreviation" : "COL",
          "state" : "Colorado",
          "prestige" : "75",
          "name" : "Colorado",
          "headCoach" : {
            "ratOff" : "63",
            "contractLength" : "6",
            "age" : "53",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "67",
            "homeState" : "Florida",
            "ratPot" : "89",
            "ratTalent" : "70",
            "ratDiscipline" : "54",
            "baselinePrestige" : "55",
            "ratOvr" : "63",
            "name" : "Richard Hoznour",
            "contractYear" : "1"
          },
          "rival" : "AF"
        },
        {
          "abbreviation" : "UNLV",
          "state" : "Nevada",
          "prestige" : "40",
          "name" : "UNLV",
          "headCoach" : {
            "ratOff" : "72",
            "contractLength" : "6",
            "age" : "33",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "81",
            "homeState" : "Utah",
            "ratPot" : "56",
            "ratTalent" : "54",
            "ratDiscipline" : "47",
            "baselinePrestige" : "65",
            "ratOvr" : "63",
            "name" : "Ralph Mcburnie",
            "contractYear" : "1"
          },
          "rival" : "BS"
        },
        {
          "abbreviation" : "BS",
          "state" : "Idaho",
          "prestige" : "70",
          "name" : "Boise State",
          "headCoach" : {
            "ratOff" : "59",
            "contractLength" : "6",
            "age" : "38",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "75",
            "homeState" : "Minnesota",
            "ratPot" : "53",
            "ratTalent" : "46",
            "ratDiscipline" : "56",
            "baselinePrestige" : "65",
            "ratOvr" : "59",
            "name" : "Donnell Shalam",
            "contractYear" : "1"
          },
          "rival" : "UNLV"
        },
        {
          "abbreviation" : "ASU",
          "state" : "Arizona",
          "prestige" : "80",
          "name" : "Arizona State",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "39",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Alaska",
            "ratPot" : "89",
            "ratTalent" : "50",
            "ratDiscipline" : "63",
            "baselinePrestige" : "55",
            "ratOvr" : "61",
            "name" : "Harvey Sprandel",
            "contractYear" : "1"
          },
          "rival" : "AZ"
        },
        {
          "abbreviation" : "AZ",
          "state" : "Arizona",
          "prestige" : "58",
          "name" : "Arizona",
          "headCoach" : {
            "ratOff" : "65",
            "contractLength" : "6",
            "age" : "49",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "59",
            "homeState" : "Maryland",
            "ratPot" : "54",
            "ratTalent" : "73",
            "ratDiscipline" : "52",
            "baselinePrestige" : "65",
            "ratOvr" : "62",
            "name" : "JR Sowa",
            "contractYear" : "1"
          },
          "rival" : "ASU"
        }
      ],
      "confFullName" : "Mountain West",
      "confPrestige" : "80",
      "confName" : "MWC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "ARMY",
          "state" : "New York",
          "prestige" : "61",
          "name" : "Army",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "39",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "61",
            "homeState" : "Indiana",
            "ratPot" : "65",
            "ratTalent" : "94",
            "ratDiscipline" : "73",
            "baselinePrestige" : "50",
            "ratOvr" : "72",
            "name" : "Scott Gorny",
            "contractYear" : "1"
          },
          "rival" : "NAVY"
        },
        {
          "abbreviation" : "NAVY",
          "state" : "Maryland",
          "prestige" : "60",
          "name" : "Navy",
          "headCoach" : {
            "ratOff" : "78",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Maryland",
            "ratPot" : "61",
            "ratTalent" : "70",
            "ratDiscipline" : "59",
            "baselinePrestige" : "50",
            "ratOvr" : "66",
            "name" : "Amir Nordick",
            "contractYear" : "1"
          },
          "rival" : "ARMY"
        },
        {
          "abbreviation" : "CUSE",
          "state" : "New York",
          "prestige" : "55",
          "name" : "Syracuse",
          "headCoach" : {
            "ratOff" : "76",
            "contractLength" : "6",
            "age" : "41",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "78",
            "homeState" : "Delaware",
            "ratPot" : "68",
            "ratTalent" : "52",
            "ratDiscipline" : "51",
            "baselinePrestige" : "80",
            "ratOvr" : "64",
            "name" : "Terrence Woodworth",
            "contractYear" : "1"
          },
          "rival" : "USF"
        },
        {
          "abbreviation" : "RUTG",
          "state" : "New Jersey",
          "prestige" : "55",
          "name" : "Rutgers",
          "headCoach" : {
            "ratOff" : "58",
            "contractLength" : "6",
            "age" : "45",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Connecticut",
            "ratPot" : "91",
            "ratTalent" : "47",
            "ratDiscipline" : "51",
            "baselinePrestige" : "70",
            "ratOvr" : "53",
            "name" : "Damon Declerk",
            "contractYear" : "1"
          },
          "rival" : "TEMP"
        },
        {
          "abbreviation" : "PITT",
          "state" : "Pennsylvania",
          "prestige" : "65",
          "name" : "Pittsburgh",
          "headCoach" : {
            "ratOff" : "60",
            "contractLength" : "6",
            "age" : "55",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Iowa",
            "ratPot" : "84",
            "ratTalent" : "88",
            "ratDiscipline" : "53",
            "baselinePrestige" : "55",
            "ratOvr" : "67",
            "name" : "Bradley Ramagano",
            "contractYear" : "1"
          },
          "rival" : "CUSE"
        },
        {
          "abbreviation" : "BC",
          "state" : "Massachusetts",
          "prestige" : "70",
          "name" : "Boston College",
          "headCoach" : {
            "ratOff" : "63",
            "contractLength" : "6",
            "age" : "52",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "64",
            "homeState" : "Massachusetts",
            "ratPot" : "67",
            "ratTalent" : "83",
            "ratDiscipline" : "68",
            "baselinePrestige" : "75",
            "ratOvr" : "69",
            "name" : "Greg Shippy",
            "contractYear" : "1"
          },
          "rival" : "UCONN"
        },
        {
          "abbreviation" : "TEMP",
          "state" : "Pennsylvania",
          "prestige" : "50",
          "name" : "Temple",
          "headCoach" : {
            "ratOff" : "77",
            "contractLength" : "6",
            "age" : "54",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Rhode Island",
            "ratPot" : "77",
            "ratTalent" : "49",
            "ratDiscipline" : "93",
            "baselinePrestige" : "65",
            "ratOvr" : "72",
            "name" : "Jonah Bricker",
            "contractYear" : "1"
          },
          "rival" : "RUTG"
        },
        {
          "abbreviation" : "UCONN",
          "state" : "Connecticut",
          "prestige" : "40",
          "name" : "UConn",
          "headCoach" : {
            "ratOff" : "66",
            "contractLength" : "6",
            "age" : "35",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "Illinois",
            "ratPot" : "69",
            "ratTalent" : "87",
            "ratDiscipline" : "45",
            "baselinePrestige" : "70",
            "ratOvr" : "67",
            "name" : "Louis Illig",
            "contractYear" : "1"
          },
          "rival" : "BC"
        },
        {
          "abbreviation" : "PSU",
          "state" : "Pennsylvania",
          "prestige" : "90",
          "name" : "Penn State",
          "headCoach" : {
            "ratOff" : "73",
            "contractLength" : "6",
            "age" : "54",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "80",
            "homeState" : "Missouri",
            "ratPot" : "56",
            "ratTalent" : "45",
            "ratDiscipline" : "93",
            "baselinePrestige" : "70",
            "ratOvr" : "72",
            "name" : "Joe Tryner",
            "contractYear" : "1"
          },
          "rival" : "MARY"
        },
        {
          "abbreviation" : "MARY",
          "state" : "Maryland",
          "prestige" : "69",
          "name" : "Maryland",
          "headCoach" : {
            "ratOff" : "59",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "63",
            "homeState" : "Virginia",
            "ratPot" : "72",
            "ratTalent" : "56",
            "ratDiscipline" : "91",
            "baselinePrestige" : "70",
            "ratOvr" : "67",
            "name" : "Jerry Burnette",
            "contractYear" : "1"
          },
          "rival" : "PSU"
        }
      ],
      "confFullName" : "Northeast",
      "confPrestige" : "85",
      "confName" : "NEC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "BAMA",
          "state" : "Alabama",
          "prestige" : "95",
          "name" : "Alabama",
          "headCoach" : {
            "ratOff" : "88",
            "contractLength" : "6",
            "age" : "47",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "74",
            "homeState" : "Nebraska",
            "ratPot" : "79",
            "ratTalent" : "45",
            "ratDiscipline" : "47",
            "baselinePrestige" : "75",
            "ratOvr" : "81",
            "name" : "Levi Haley",
            "contractYear" : "1"
          },
          "rival" : "AUB"
        },
        {
          "abbreviation" : "AUB",
          "state" : "Alabama",
          "prestige" : "90",
          "name" : "Auburn",
          "headCoach" : {
            "ratOff" : "53",
            "contractLength" : "6",
            "age" : "49",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "67",
            "homeState" : "Missouri",
            "ratPot" : "61",
            "ratTalent" : "56",
            "ratDiscipline" : "88",
            "baselinePrestige" : "65",
            "ratOvr" : "66",
            "name" : "Trey Robbins",
            "contractYear" : "1"
          },
          "rival" : "BAMA"
        },
        {
          "abbreviation" : "ARK",
          "state" : "Arkansas",
          "prestige" : "80",
          "name" : "Arkansas",
          "headCoach" : {
            "ratOff" : "75",
            "contractLength" : "6",
            "age" : "54",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "62",
            "homeState" : "Georgia",
            "ratPot" : "50",
            "ratTalent" : "82",
            "ratDiscipline" : "71",
            "baselinePrestige" : "75",
            "ratOvr" : "72",
            "name" : "Greg Mausser",
            "contractYear" : "1"
          },
          "rival" : "LSU"
        },
        {
          "abbreviation" : "LSU",
          "state" : "Louisiana",
          "prestige" : "95",
          "name" : "LSU",
          "headCoach" : {
            "ratOff" : "70",
            "contractLength" : "6",
            "age" : "47",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "Missouri",
            "ratPot" : "50",
            "ratTalent" : "92",
            "ratDiscipline" : "50",
            "baselinePrestige" : "55",
            "ratOvr" : "71",
            "name" : "John Smith",
            "contractYear" : "1"
          },
          "rival" : "ARK"
        },
        {
          "abbreviation" : "MSST",
          "state" : "Mississippi",
          "prestige" : "82",
          "name" : "Mississippi State",
          "headCoach" : {
            "ratOff" : "62",
            "contractLength" : "6",
            "age" : "36",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "California",
            "ratPot" : "67",
            "ratTalent" : "60",
            "ratDiscipline" : "84",
            "baselinePrestige" : "60",
            "ratOvr" : "69",
            "name" : "Russell Adelsperger",
            "contractYear" : "1"
          },
          "rival" : "OLEM"
        },
        {
          "abbreviation" : "OLEM",
          "state" : "Mississippi",
          "prestige" : "80",
          "name" : "Ole Miss",
          "headCoach" : {
            "ratOff" : "61",
            "contractLength" : "6",
            "age" : "38",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Wisconsin",
            "ratPot" : "65",
            "ratTalent" : "82",
            "ratDiscipline" : "73",
            "baselinePrestige" : "65",
            "ratOvr" : "68",
            "name" : "Ira Crichlow",
            "contractYear" : "1"
          },
          "rival" : "MSST"
        },
        {
          "abbreviation" : "MEM",
          "state" : "Tennessee",
          "prestige" : "60",
          "name" : "Memphis",
          "headCoach" : {
            "ratOff" : "74",
            "contractLength" : "6",
            "age" : "48",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "66",
            "homeState" : "Delaware",
            "ratPot" : "94",
            "ratTalent" : "82",
            "ratDiscipline" : "54",
            "baselinePrestige" : "65",
            "ratOvr" : "69",
            "name" : "Randall Schalow",
            "contractYear" : "1"
          },
          "rival" : "TULN"
        },
        {
          "abbreviation" : "TULN",
          "state" : "Louisiana",
          "prestige" : "40",
          "name" : "Tulane",
          "headCoach" : {
            "ratOff" : "57",
            "contractLength" : "6",
            "age" : "34",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "75",
            "homeState" : "North Carolina",
            "ratPot" : "95",
            "ratTalent" : "53",
            "ratDiscipline" : "60",
            "baselinePrestige" : "65",
            "ratOvr" : "61",
            "name" : "Tariq Masiejczyk",
            "contractYear" : "1"
          },
          "rival" : "MEM"
        },
        {
          "abbreviation" : "ULL",
          "state" : "Louisiana",
          "prestige" : "40",
          "name" : "Louisiana",
          "headCoach" : {
            "ratOff" : "62",
            "contractLength" : "6",
            "age" : "37",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Idaho",
            "ratPot" : "51",
            "ratTalent" : "72",
            "ratDiscipline" : "80",
            "baselinePrestige" : "55",
            "ratOvr" : "71",
            "name" : "Bryant Trest",
            "contractYear" : "1"
          },
          "rival" : "AKST"
        },
        {
          "abbreviation" : "AKST",
          "state" : "Arkansas",
          "prestige" : "36",
          "name" : "Arkansas State",
          "headCoach" : {
            "ratOff" : "63",
            "contractLength" : "6",
            "age" : "47",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "54",
            "homeState" : "Georgia",
            "ratPot" : "95",
            "ratTalent" : "68",
            "ratDiscipline" : "55",
            "baselinePrestige" : "60",
            "ratOvr" : "60",
            "name" : "Tre Sulc",
            "contractYear" : "1"
          },
          "rival" : "ULL"
        }
      ],
      "confFullName" : "Southeastern",
      "confPrestige" : "88",
      "confName" : "SEC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "HARV",
          "state" : "Massachusetts",
          "prestige" : "65",
          "name" : "Harvard",
          "headCoach" : {
            "ratOff" : "56",
            "contractLength" : "6",
            "age" : "30",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "61",
            "homeState" : "North Dakota",
            "ratPot" : "80",
            "ratTalent" : "48",
            "ratDiscipline" : "74",
            "baselinePrestige" : "55",
            "ratOvr" : "59",
            "name" : "Grant Cioffi",
            "contractYear" : "1"
          },
          "rival" : "COLM"
        },
        {
          "abbreviation" : "COLM",
          "state" : "New York",
          "prestige" : "65",
          "name" : "Columbia",
          "headCoach" : {
            "ratOff" : "54",
            "contractLength" : "6",
            "age" : "45",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "57",
            "homeState" : "Idaho",
            "ratPot" : "88",
            "ratTalent" : "78",
            "ratDiscipline" : "52",
            "baselinePrestige" : "55",
            "ratOvr" : "60",
            "name" : "Joseph Szitar",
            "contractYear" : "1"
          },
          "rival" : "HARV"
        },
        {
          "abbreviation" : "DART",
          "state" : "New Hampshire",
          "prestige" : "55",
          "name" : "Dartmouth",
          "headCoach" : {
            "ratOff" : "59",
            "contractLength" : "6",
            "age" : "42",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "60",
            "homeState" : "Alaska",
            "ratPot" : "79",
            "ratTalent" : "71",
            "ratDiscipline" : "70",
            "baselinePrestige" : "50",
            "ratOvr" : "65",
            "name" : "Dwayne Frediani",
            "contractYear" : "1"
          },
          "rival" : "BRO"
        },
        {
          "abbreviation" : "BRO",
          "state" : "Rhode Island",
          "prestige" : "55",
          "name" : "Brown",
          "headCoach" : {
            "ratOff" : "68",
            "contractLength" : "6",
            "age" : "57",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "73",
            "homeState" : "Texas",
            "ratPot" : "86",
            "ratTalent" : "69",
            "ratDiscipline" : "66",
            "baselinePrestige" : "70",
            "ratOvr" : "69",
            "name" : "Isidro Krenning",
            "contractYear" : "1"
          },
          "rival" : "DART"
        },
        {
          "abbreviation" : "PENN",
          "state" : "Pennsylvania",
          "prestige" : "60",
          "name" : "Pennsylvania",
          "headCoach" : {
            "ratOff" : "66",
            "contractLength" : "6",
            "age" : "54",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "57",
            "homeState" : "Vermont",
            "ratPot" : "87",
            "ratTalent" : "48",
            "ratDiscipline" : "91",
            "baselinePrestige" : "60",
            "ratOvr" : "65",
            "name" : "Wyatt Longhenry",
            "contractYear" : "1"
          },
          "rival" : "PRIN"
        },
        {
          "abbreviation" : "PRIN",
          "state" : "New Jersey",
          "prestige" : "60",
          "name" : "Princeton",
          "headCoach" : {
            "ratOff" : "58",
            "contractLength" : "6",
            "age" : "41",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "60",
            "homeState" : "Minnesota",
            "ratPot" : "50",
            "ratTalent" : "54",
            "ratDiscipline" : "82",
            "baselinePrestige" : "65",
            "ratOvr" : "63",
            "name" : "Mac Ehrisman",
            "contractYear" : "1"
          },
          "rival" : "PENN"
        },
        {
          "abbreviation" : "YALE",
          "state" : "Connecticut",
          "prestige" : "60",
          "name" : "Yale",
          "headCoach" : {
            "ratOff" : "66",
            "contractLength" : "6",
            "age" : "49",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "71",
            "homeState" : "Alaska",
            "ratPot" : "66",
            "ratTalent" : "79",
            "ratDiscipline" : "79",
            "baselinePrestige" : "70",
            "ratOvr" : "73",
            "name" : "Cedrick Nagarajan",
            "contractYear" : "1"
          },
          "rival" : "CORN"
        },
        {
          "abbreviation" : "CORN",
          "state" : "New York",
          "prestige" : "60",
          "name" : "Cornell",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "51",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "75",
            "homeState" : "South Dakota",
            "ratPot" : "73",
            "ratTalent" : "87",
            "ratDiscipline" : "48",
            "baselinePrestige" : "65",
            "ratOvr" : "68",
            "name" : "William Mohr",
            "contractYear" : "1"
          },
          "rival" : "YALE"
        },
        {
          "abbreviation" : "TRIN",
          "state" : "Connecticut",
          "prestige" : "30",
          "name" : "Trinity",
          "headCoach" : {
            "ratOff" : "78",
            "contractLength" : "6",
            "age" : "41",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "76",
            "homeState" : "Delaware",
            "ratPot" : "90",
            "ratTalent" : "78",
            "ratDiscipline" : "94",
            "baselinePrestige" : "65",
            "ratOvr" : "81",
            "name" : "Brian Pierce",
            "contractYear" : "1"
          },
          "rival" : "HAM"
        },
        {
          "abbreviation" : "HAM",
          "state" : "New York",
          "prestige" : "30",
          "name" : "Hamilton",
          "headCoach" : {
            "ratOff" : "67",
            "contractLength" : "6",
            "age" : "31",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "61",
            "homeState" : "South Dakota",
            "ratPot" : "51",
            "ratTalent" : "50",
            "ratDiscipline" : "63",
            "baselinePrestige" : "65",
            "ratOvr" : "60",
            "name" : "Harold Zerhusen",
            "contractYear" : "1"
          },
          "rival" : "TRIN"
        }
      ],
      "confFullName" : "Ivy League",
      "confPrestige" : "70",
      "confName" : "IVY"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "ND",
          "state" : "Indiana",
          "prestige" : "95",
          "name" : "Notre Dame",
          "headCoach" : {
            "ratOff" : "80",
            "contractLength" : "6",
            "age" : "37",
            "startYear" : "2019",
            "cumulativePrestige" : "45",
            "ratDef" : "83",
            "homeState" : "Nebraska",
            "ratPot" : "86",
            "ratTalent" : "79",
            "ratDiscipline" : "58",
            "baselinePrestige" : "70",
            "ratOvr" : "77",
            "name" : "Santana Hansen",
            "contractYear" : "1"
          },
          "rival" : "UMASS"
        },
        {
          "abbreviation" : "UMASS",
          "state" : "Massachusetts",
          "prestige" : "50",
          "name" : "UMASS",
          "headCoach" : {
            "ratOff" : "77",
            "contractLength" : "6",
            "age" : "38",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "80",
            "homeState" : "Montana",
            "ratPot" : "56",
            "ratTalent" : "79",
            "ratDiscipline" : "92",
            "baselinePrestige" : "65",
            "ratOvr" : "82",
            "name" : "Greg Pittenger",
            "contractYear" : "1"
          },
          "rival" : "ND"
        },
        {
          "abbreviation" : "NEV",
          "state" : "Nevada",
          "prestige" : "50",
          "name" : "Nevada",
          "headCoach" : {
            "ratOff" : "71",
            "contractLength" : "6",
            "age" : "48",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "73",
            "homeState" : "Louisiana",
            "ratPot" : "68",
            "ratTalent" : "86",
            "ratDiscipline" : "51",
            "baselinePrestige" : "60",
            "ratOvr" : "70",
            "name" : "Javarious Montagna",
            "contractYear" : "1"
          },
          "rival" : "FRES"
        },
        {
          "abbreviation" : "FRES",
          "state" : "California",
          "prestige" : "49",
          "name" : "Fresno State",
          "headCoach" : {
            "ratOff" : "57",
            "contractLength" : "6",
            "age" : "45",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "74",
            "homeState" : "Iowa",
            "ratPot" : "69",
            "ratTalent" : "92",
            "ratDiscipline" : "79",
            "baselinePrestige" : "65",
            "ratOvr" : "75",
            "name" : "Renard Rubash",
            "contractYear" : "1"
          },
          "rival" : "NEV"
        },
        {
          "abbreviation" : "USU",
          "state" : "Utah",
          "prestige" : "47",
          "name" : "Utah State",
          "headCoach" : {
            "ratOff" : "63",
            "contractLength" : "6",
            "age" : "46",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "68",
            "homeState" : "Illinois",
            "ratPot" : "92",
            "ratTalent" : "74",
            "ratDiscipline" : "70",
            "baselinePrestige" : "50",
            "ratOvr" : "68",
            "name" : "Jaden Uselman",
            "contractYear" : "1"
          },
          "rival" : "UNM"
        },
        {
          "abbreviation" : "UNM",
          "state" : "New Mexico",
          "prestige" : "46",
          "name" : "New Mexico",
          "headCoach" : {
            "ratOff" : "59",
            "contractLength" : "6",
            "age" : "38",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "51",
            "homeState" : "Virginia",
            "ratPot" : "83",
            "ratTalent" : "80",
            "ratDiscipline" : "73",
            "baselinePrestige" : "55",
            "ratOvr" : "65",
            "name" : "Clint Baik",
            "contractYear" : "1"
          },
          "rival" : "USU"
        },
        {
          "abbreviation" : "UAB",
          "state" : "Alabama",
          "prestige" : "38",
          "name" : "UAB",
          "headCoach" : {
            "ratOff" : "65",
            "contractLength" : "6",
            "age" : "44",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "62",
            "homeState" : "Florida",
            "ratPot" : "58",
            "ratTalent" : "76",
            "ratDiscipline" : "58",
            "baselinePrestige" : "65",
            "ratOvr" : "65",
            "name" : "Andre Pola",
            "contractYear" : "1"
          },
          "rival" : "BUFF"
        },
        {
          "abbreviation" : "BUFF",
          "state" : "New York",
          "prestige" : "50",
          "name" : "Buffalo",
          "headCoach" : {
            "ratOff" : "64",
            "contractLength" : "6",
            "age" : "31",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "70",
            "homeState" : "Ohio",
            "ratPot" : "61",
            "ratTalent" : "83",
            "ratDiscipline" : "62",
            "baselinePrestige" : "55",
            "ratOvr" : "69",
            "name" : "Avery Underdahl",
            "contractYear" : "1"
          },
          "rival" : "UAB"
        },
        {
          "abbreviation" : "RICE",
          "state" : "Texas",
          "prestige" : "55",
          "name" : "Rice",
          "headCoach" : {
            "ratOff" : "62",
            "contractLength" : "6",
            "age" : "42",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "58",
            "homeState" : "Georgia",
            "ratPot" : "60",
            "ratTalent" : "45",
            "ratDiscipline" : "85",
            "baselinePrestige" : "55",
            "ratOvr" : "62",
            "name" : "Jason Jens",
            "contractYear" : "1"
          },
          "rival" : "TUL"
        },
        {
          "abbreviation" : "TUL",
          "state" : "Oklahoma",
          "prestige" : "55",
          "name" : "Tulsa",
          "headCoach" : {
            "ratOff" : "56",
            "contractLength" : "6",
            "age" : "52",
            "startYear" : "2019",
            "cumulativePrestige" : "25",
            "ratDef" : "63",
            "homeState" : "Maine",
            "ratPot" : "93",
            "ratTalent" : "74",
            "ratDiscipline" : "78",
            "baselinePrestige" : "55",
            "ratOvr" : "67",
            "name" : "Dakota Mascio",
            "contractYear" : "1"
          },
          "rival" : "RICE"
        }
      ],
      "confFullName" : "Independents",
      "confPrestige" : "79",
      "confName" : "IND"
    }
  ],
  "bowlGames" : [
    "Rose Bowl",
    "Orange Bowl",
    "Sugar Bowl",
    "Cotton Bowl",
    "Peach Bowl",
    "Fiesta Bowl",
    "Sun Bowl",
    "Gator Bowl",
    "Citrus Bowl",
    "Liberty Bowl",
    "Independence Bowl",
    "Holiday Bowl",
    "Outback Bowl",
    "Cactus Bowl",
    "Las Vegas Bowl",
    "Alamo Bowl",
    "Potato Bowl",
    "Music City Bowl",
    "GoDaddy Bowl",
    "Hawai'i Bowl",
    "Belk Bowl",
    "Armed Forces Bowl",
    "Texas Bowl",
    "Birmingham Bowl",
    "New Mexico Bowl",
    "Military Bowl",
    "Bitcoin Bowl",
    "Pinstripe Bowl",
    "Heart of Dallas Bowl",
    "Bahamas Bowl",
    "Boca Raton Bowl",
    "Athletic Bowl",
    "Foster Farms Bowl",
    "Quick Lane Bowl",
    "Poinsettia Bowl",
    "San Juan Bowl"
  ]
}
